### ISSUE TITLE
Question regarding basey

### ISSUE THREAD

**Issue by GraphicsHunter** [CedricGuillemet/imgInspect#1]
Hi,

While reading through the source, I was starting to wonder about the following line:

https://github.com/CedricGuillemet/imgInspect/blob/7c7778f060000cce230df5e0abb63c3292740b1e/imgInspect.h#L143

Why is `basey` subtracted by `zoomSize * 2 - 1` while `basex` is not? And why do you thereafter 'undo' subtraction in in
https://github.com/CedricGuillemet/imgInspect/blob/7c7778f060000cce230df5e0abb63c3292740b1e/imgInspect.h#L148
Where you 'undo' the subtraction by adding the same value.

**Comment by CedricGuillemet** [comment]
Yes, I'm wondering too now. I'll try to simplify this today. also regarding https://github.com/CedricGuillemet/imgInspect/blob/7c7778f060000cce230df5e0abb63c3292740b1e/imgInspect.h#L181 . looks strange indeed.

**Comment by CedricGuillemet** [comment]
I cleaned the code. It's a bit better now :)

**Comment by GraphicsHunter** [comment]
Awesome! The code makes a lot more sense to me now. I'll close the issue, thanks for clearing it up :)
